<a href="https://colab.research.google.com/github/themadan/get-clean-explore-data/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [3]:
a=np.arange(15)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
b.shape

(3, 5)

In [6]:
b.ndim #ndarray.ndim the number of axes (dimensions) of the array

2

In [7]:
b.dtype.name 

'int64'

In [8]:
b.size #ndarray.size the total number of elements of the array. This is equal to the product of the elements of shape.

15

In [9]:
b.itemsize #the size of bytes of each element of the array.

8

In [10]:
type(b)

numpy.ndarray

# **Array Creation** auta (=[ hunxa

In [11]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [12]:
c.dtype


dtype('int64')

In [13]:
c=np.array([1.2,2.1,3.1])
c

array([1.2, 2.1, 3.1])

In [14]:
c.dtype

dtype('float64')

In [15]:
a=np.array([('R1C1','R1C2'),('R2C1','R2C2')]) #two dimention array
a

array([['R1C1', 'R1C2'],
       ['R2C1', 'R2C2']], dtype='<U4')

In [16]:
a=np.array([[1,2],[3,4]],dtype=complex) #complex data type specified
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

np.empty((4,5)) #empty so randomly initialize

In [20]:
np.arange(10,30,5) # 10 bata start 30 exclude 5 le increase garni

array([10, 15, 20, 25])

In [22]:
np.arange(2,5,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [24]:
np.linspace(0,5,5) #0 dakhi 5 samma 5 ota number

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [0]:
from numpy import pi
x=np.linspace(0,2*pi,100)
f=np.sin(x)

# **Printing array**

In [28]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [31]:
a=np.arange(12).reshape(4,3) #2d array
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [32]:
a=np.arange(24).reshape(2,3,4) #3d array
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [34]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# **Basic operation**