# **Tensorflow**
# key : tf.modulename.functionanae(parameters)
# key :  tensor <=>anydata  (yasari any data lai tensor(matrix) ra any tensor(matrix) lai data ma convert garxa  
[tensofflow for python ](https://www.tensorflow.org/)

# **STEPS** (TensorFlow ecosystem) [read step by step form tensorflow ecosystem](https://www.tensorflow.org/learn)
#C=create input piplines/Load & preprocess data
#R=Read Data
#U=update parameter /Build, train & reuse models
#D=Deploy model

# STEP 1:: C=Create input pipline/load & preprocess data

# A. **[tf.data](https://www.tensorflow.org/api_docs/python/tf/data)**  api enables you to build complex input pipline from single reusable pices
# B.**[tf.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset)**  abstraction represents a sequence of elements ,in which each element consists of one or more components .eg image pipline
 # i. There is two distinct ways to create Dataset .
 # * A data source construct a Dataset from data stored in memory or in one or more files.
 # * A data transformation constructs a datasets a dataset from one or more tf.data.Dataset

In [0]:
import tensorflow as tf
from __future__ import  absolute_import,division,print_function,unicode_literals

In [5]:
try :
  !pip install -q tf-nightly
except Exception:
    pass 


     |████████████████████████████████| 511.7MB 33kB/s 
     |████████████████████████████████| 3.9MB 48.6MB/s 
     |████████████████████████████████| 2.9MB 50.9MB/s 
     |████████████████████████████████| 460kB 57.8MB/s 
ERROR: tensorflow 2.0.0 has requirement gast==0.2.2, but you'll have gast 0.3.3 which is incompatible.


In [6]:
print(tf.__version__)

2.0.0


In [0]:
import pathlib
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
np.set_printoptions(precision=4)

# To create an input pipeline ,you must start with source .
# * to construct a Dataset from data in memory ,you can use 
# **tf.data.Dataset.from_tensors()** or **tf.data.Dataset.from_tensor_slices()**

In [8]:
dataset =tf.data.Dataset.from_tensor_slices([1,2,3,4])
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [16]:
for i in dataset:
  print(i.numpy())

1
2
3
4


In [19]:
it=iter(dataset) # iterator le tensor as a  input linxa and auta auta gardai element denxa.
print(next(it).numpy())

1


In [22]:
print(dataset.reduce(0,lambda state,value:state + value).numpy()) #reduce the all elements to produce a single result.

10


# Dataset Structure
# * **tf.TypeSpace** ::kun type ko ho tensor Tensor,SparseTensor,RaggedTensor,TensorArray or Dataset   Dinxa
# * **Dataset.element_spec** ::tensor ko dataset ko type of each element component denaxa 
# **note :** shape(n,)  n vanyasi dimension janauxa  x,y =2 dimension..
 # so yaha n le no of column  which represent the  dimension.

In [38]:
tf.TypeSpec


tensorflow.python.framework.type_spec.TypeSpec

In [50]:
dataset=tf.data.Dataset.from_tensor_slices(tf.random.uniform([4,10]))
# for i in dataset:
#    print(i.numpy())
dataset.element_spec # NOTE::
#print(dataset)

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [58]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2.element_spec


(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [53]:
dataset3=tf.data.Dataset.zip((dataset,dataset2))
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(900,), dtype=tf.int32, name=None)))

In [56]:
# dataset containing a sparse tensor 
dataset4=tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0,0],[1,2]],values=[1,2],dense_shape=[3,4]))
dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [57]:
# use value_type to see the type of value represented by element spec
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor

In [63]:
dataset5=tf.data.Dataset.from_tensor_slices(tf.random.uniform([4,10],maxval=10,dtype=tf.int32))
dataset5

<TensorSliceDataset shapes: (10,), types: tf.int32>

In [65]:
for z in dataset5:
  print(z.numpy())

[4 7 2 1 8 6 8 0 8 2]
[5 5 8 8 6 0 3 9 3 9]
[4 0 3 5 8 3 0 4 9 8]
[3 6 1 5 1 0 7 5 5 8]


In [69]:
dataset6 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset6

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>

# Reading input data 
# * consuming numpy arrays

In [71]:
# LOAD FROM .npz file 
DATA_URL='https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz'
path=tf.keras.utils.get_file('mnist.npz',DATA_URL)
with np.load(path) as data:
  train_examples=data['x_train']
  train_labels=data['y_train']
  test_examples=data['x_test']
  test_labels=data['y_test']

11493376/11490434 [==============================] - 0s 0us/step


![iamge here](https://raw.githubusercontent.com/themadan/1.DataScience-libraries/master/Tensorflow(nn-deep%20learning)/images/ndarray%20and%20shape.png)

In [95]:
train,test=tf.keras.datasets.fashion_mnist.load_data() # mnist data load garxa ani tuple ko rupma return garxa (x_train,y_train),(x_test,y_test) yasari return garxa.
print(train[0].shape) #x_train   (60000=no of row=no of image,28=no of row ,28=no of column)
print(train[1].shape)# y_train(labels)
print(test[0].shape)# x_test
print(test[1].shape)#y_test
print(train[0][0].shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
(28, 28)


In [0]:
images,labels=train
images=images/255


In [75]:
dataset=tf.data.Dataset.from_tensor_slices((images,labels))
dataset

<TensorSliceDataset shapes: ((28, 28), ()), types: (tf.float64, tf.uint8)>

In [92]:
li=np.array([[[1,2,3],[4,5,6]]])
print(li.shape)

(1, 2, 3)
