# NUMPY 
# 1.array
# 2.operation in array (each element in array)

In [0]:
import numpy as np

In [2]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [3]:
a=np.arange(15)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
b.shape

(3, 5)

In [6]:
b.ndim #ndarray.ndim the number of axes (dimensions) of the array

2

In [7]:
b.dtype.name 

'int64'

In [8]:
b.size #ndarray.size the total number of elements of the array. This is equal to the product of the elements of shape.

15

In [9]:
b.itemsize #the size of bytes of each element of the array.

8

In [10]:
type(b)

numpy.ndarray

# **Array Creation** 
# () yasto vaya array ko shape (row,column,step)
# ([]) yasto vaya array element janauxa ([elements of array])

In [11]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [12]:
c.dtype


dtype('int64')

In [13]:
c=np.array([1.2,2.1,3.1])
c

array([1.2, 2.1, 3.1])

In [14]:
c.dtype

dtype('float64')

In [15]:
a=np.array([('R1C1','R1C2'),('R2C1','R2C2')]) #two dimention array
a

array([['R1C1', 'R1C2'],
       ['R2C1', 'R2C2']], dtype='<U4')

In [16]:
a=np.array([[1,2],[3,4]],dtype=complex) #complex data type specified
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.empty((4,5)) #empty so randomly initialize

array([[2.59161067e-316, 5.68175493e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.16095484e-028, 4.27255707e+180, 6.19522232e+223,
        5.03734623e+180, 1.54722523e+262],
       [7.48952651e+247, 8.76739466e+252, 8.89489936e+252,
        5.54175225e+257, 6.02182527e+151],
       [9.30537465e+199, 2.20835466e-094, 5.50028887e+247,
        2.15799222e+243, 4.06021814e-317]])

In [21]:
np.arange(10,30,5) #start from 10 exclude 30 and increase by 5

array([10, 15, 20, 25])

In [22]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [0]:
from numpy import pi
np.linspace(0,2,9)
x=np.linspace(0,2*pi,100)
f=np.sin(x)

# **Printing Array**

In [25]:
print(np.arange(6))

[0 1 2 3 4 5]


In [28]:
print(np.arange(12).reshape(4,3)) #2d array

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
print(np.arange(24).reshape(2,3,4)) #3d array

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
print(np.arange(10000)) # long number lai ni short ... form ma dinxa

[   0    1    2 ... 9997 9998 9999]


# **Basic Operation 
#(broadcasting  concept most= operator ko shape same hunuparxa ani matra operation hunxa** 
# **array ko each elementwise hunxa operation ok **

In [0]:
a=np.array([20,30,40,50])
b=np.arange(4)

In [37]:
c=a-b # most note yo operation huna a ra b ko shape same hunuparxa 
c

array([20, 29, 38, 47])

In [39]:
a=np.array([20,30,40,50])
b=np.arange(3)
c=a-b       #a ra b ko shape same xaina  so operation hudaina
c

ValueError: ignored

In [41]:
a=np.array([20,30,40,50])
b=np.arange(4) 
b**2 #b ko each array element ko square

array([0, 1, 4, 9])

In [44]:
10*np.sin(a) #a array ko each element ma yo opeartion garxa

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [46]:
a<35 #a array ko each element ma yo operation garxa

array([ True,  True, False, False])

**elementwise product (note:first element le first lai,second le second lai...so on)**

In [68]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
a * b 

array([[2, 0],
       [0, 4]])

**matrix product (note :first matrix row multiply second matrix column...)** 

In [69]:
a @ b  #matrix product

array([[5, 4],
       [3, 4]])

In [70]:
a.dot(b) #matrix product

array([[5, 4],
       [3, 4]])

In [71]:
a*=3 #modify existing array
a

array([[3, 3],
       [0, 3]])

In [72]:
a+=b
a

array([[5, 3],
       [3, 7]])

In [73]:
d=np.exp(a*1j)
d

array([[ 0.28366219-0.95892427j, -0.9899925 +0.14112001j],
       [-0.9899925 +0.14112001j,  0.75390225+0.6569866j ]])

In [74]:
a=np.random.random((2,3))
a

array([[0.89112411, 0.98543517, 0.9984008 ],
       [0.44422512, 0.71656147, 0.34978721]])

In [75]:
a.sum()

4.385533880231202

In [77]:
a.min()

0.3497872079362323

In [78]:
a.max()

0.9984008035554077

In [79]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# axis=1 is row
# axis=0 is column

In [80]:
b.sum(axis=0) #sum of each column

array([12, 15, 18, 21])

In [82]:
b.min(axis=1) #min of each row

array([0, 4, 8])

In [84]:
b.cumsum(axis=1) # cumulative sum along each row 
#last ma sabai row element ko sum niskinxa

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# **Universal functions**

In [85]:
b=np.arange(3)
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [86]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [87]:
c=np.arange(3)
np.add(b,c)

array([0, 2, 4])

# **Indexing,slicing and iterating**
# **[startindex:endindex:stepindex]**

much like list in python

# one-dimensional


In [88]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [89]:
a[2]

8

In [91]:
a[2:5] #2 include dekhi 5 exclude index samma ko elements haru

array([ 8, 27, 64])

In [93]:
a[:6:2]=-1000 # equivalent to a[0:6:2] = -1000
# from start to position 6,exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [94]:
a[::-1] #reverse a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

# Multidimensional

# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas: