In [0]:
import numpy as np

In [0]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [0]:
a=np.arange(15)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
b.shape

(3, 5)

In [0]:
b.ndim #ndarray.ndim the number of axes (dimensions) of the array

2

In [0]:
b.dtype.name 

'int64'

In [0]:
b.size #ndarray.size the total number of elements of the array. This is equal to the product of the elements of shape.

15

In [0]:
b.itemsize #the size of bytes of each element of the array.

8

In [0]:
type(b)

numpy.ndarray

**Array Creation**

In [0]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [0]:
c.dtype


dtype('int64')

In [0]:
c=np.array([1.2,2.1,3.1])
c

array([1.2, 2.1, 3.1])

In [0]:
c.dtype

dtype('float64')

In [0]:
a=np.array([('R1C1','R1C2'),('R2C1','R2C2')]) #two dimention array
a

array([['R1C1', 'R1C2'],
       ['R2C1', 'R2C2']], dtype='<U4')

In [0]:
a=np.array([[1,2],[3,4]],dtype=complex) #complex data type specified
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [0]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
np.empty((4,5)) #empty so randomly initialize

array([[0.00000000e+000, 5.38531554e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.16095484e-028, 3.68423986e+180, 5.56218858e+180,
        1.54722523e+262, 7.48952651e+247],
       [8.76739466e+252, 8.89489936e+252, 1.17149199e+214,
        1.14428494e+243, 1.35617218e+248],
       [2.78225511e+296, 7.67127212e+151, 2.77620488e+184,
        6.20590572e+228, 2.65690676e-312]])