In [0]:
import numpy as np

In [2]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [3]:
a=np.arange(15)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
b.shape

(3, 5)

In [6]:
b.ndim #ndarray.ndim the number of axes (dimensions) of the array

2

In [7]:
b.dtype.name 

'int64'

In [8]:
b.size #ndarray.size the total number of elements of the array. This is equal to the product of the elements of shape.

15

In [9]:
b.itemsize #the size of bytes of each element of the array.

8

In [10]:
type(b)

numpy.ndarray

**Array Creation**

In [11]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [12]:
c.dtype


dtype('int64')

In [13]:
c=np.array([1.2,2.1,3.1])
c

array([1.2, 2.1, 3.1])

In [14]:
c.dtype

dtype('float64')

In [15]:
a=np.array([('R1C1','R1C2'),('R2C1','R2C2')]) #two dimention array
a

array([['R1C1', 'R1C2'],
       ['R2C1', 'R2C2']], dtype='<U4')

In [16]:
a=np.array([[1,2],[3,4]],dtype=complex) #complex data type specified
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.empty((4,5)) #empty so randomly initialize

array([[2.59161067e-316, 5.68175493e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.16095484e-028, 4.27255707e+180, 6.19522232e+223,
        5.03734623e+180, 1.54722523e+262],
       [7.48952651e+247, 8.76739466e+252, 8.89489936e+252,
        5.54175225e+257, 6.02182527e+151],
       [9.30537465e+199, 2.20835466e-094, 5.50028887e+247,
        2.15799222e+243, 4.06021814e-317]])

In [21]:
np.arange(10,30,5) #start from 10 exclude 30 and increase by 5

array([10, 15, 20, 25])